c
c     FILE: modelcomm2.f                    Creation date: 25/OCT/1997.
c                                       LAST MODIFICATION: 01/MAR/2002.
c
c     This file contains the definitions of the arrays used for
c     temporary storage of secondary particles, and related data.
c
c     Written by: S. J. Sciutto, La Plata 1997, 1998, 2002.
c
co---oo---oo---oo---oo---oo---oo---o*o---oo---oo---oo---oo---oo---oo---o
co---oo---oo---oo---oo---oo---oo---o*o---oo---oo---oo---oo---oo---oo---o
c
c     Temporary storage area for secondaries generated by external
c     collision routines.
c
c     Size of arrays.
c
      integer           maxsecpcles
      parameter         (maxsecpcles = 32000)
c
      integer           nsec
      integer           seccode(maxsecpcles)
      double precision  esec(maxsecpcles)
      double precision  upsec(3, maxsecpcles)
      integer           secgen(maxsecpcles)
      double precision  wa(maxsecpcles)
c
      common            /secaux_c0/ esec, upsec, seccode, nsec
      common            /secaux_c1/ wa, secgen
c
co---oo---oo---oo---oo---oo---oo---o*o---oo---oo---oo---oo---oo---oo---o
co---oo---oo---oo---oo---oo---oo---o*o---oo---oo---oo---oo---oo---oo---o
c
c     End of file 'modelcomm2.f'
c     This source file is part of AIRES 2.8.4a distribution.
c
c     Ay48299427284ay 0 Tue Dec 12 16:29:48 ART 2006
